### ISSUE TITLE
Refactor Golem actions

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#106]
Proposed new, renamed and removed actions

**New Actions**
- assert
- assert_*
- go_back
- set_search_timeout
- get_search_timeout
- double_click
- drag_and_drop
- focus_element
- close_all_browsers
- set_trace
- error
- execute_javascript
- fail
- javascript_click
- deselect_option_by_text
- deselect_option_by_value
- deselect_option_by_index
- verify_selected_option_by_text
- verify_selected_option_by_value
- get_alert_text
- send_text_to_alert
- submit_prompt_alert
- verify_alert_present
- verify_alert_not_present
- verify_alert_text
- verify_alert_text_is_not
- wait_for_alert_present
- verify_element_has_attribute
- verify_element_has_not_attribute
- verify_page_not_contains_text
- verify_element_text_contains
- verify_element_text_is_not
- verify_element_text_not_contains
- verify_title
- verify_title_contains
- verify_title_is_not
- verify_title_not_contains
- verify_url
- verify_url_contains
- verify_url_is_not
- verify_url_not_contains
- wait_for_element_present
- wait_for_element_not_enabled
- wait_for_page_contains_text
- wait_for_page_not_contains_text
- wait_for_element_text
- wait_for_element_text_is_not
- wait_for_element_contains_text
- wait_for_element_not_contains_text
- wait_for_element_has_attribute
- wait_for_element_has_not_attribute
- wait_for_alert_present
- wait_for_alert_not_present
- wait_for_title
- wait_for_title_is_not
- wait_for_title_contains
- wait_for_title_not_contains
- verify_element_attribute
- verify_element_attribute_is_not
- go_forward
- check_element
- uncheck_element
- submit_form
- switch_to_default_content
- switch_to_frame
- switch_to_parent_frame
- get_window_titles
- get_window_handle
- get_window_handles
- get_window_index
- switch_to_first_window
- switch_to_last_window
- switch_to_window_by_index
- switch_to_window_by_title
- switch_to_window_by_partial_title
- switch_to_window_by_url
- switch_to_window_by_partial_url
- switch_to_next_window
- switch_to_previous_window
- close_window
- close_window_by_index
- close_window_by_title
- close_window_by_url
- close_window_by_partial_title
- close_window_by_partial_url
- verify_window_present_by_title
- verify_window_present_by_partial_title
- verify_window_present_by_url
- verify_window_present_by_partial_url
- verify_amount_of_windows
- wait_for_window_present_by_title
- wait_for_window_present_by_partial_title
- wait_for_window_present_by_url
- wait_for_window_present_by_partial_url
- wait_for_window_not_present_title
- wait_for_window_not_present_url
- wait_for_window_not_present_partial_title
- wait_for_window_not_present_partial_url
- wait_for_amount_of_windows
- maximize_window
- get_element_text
- get_element_value
- verify_element_has_focus
- verify_element_has_not_focus
- get_element_attribute

**Renamed Actions**
- capture -> take_screenshot
- clear -> clear_element
- close -> close_browser
- debug -> interactive_mode
- mouse_hover -> mouse_over
- select_by_index -> select_option_by_index
- select_by_text -> select_option_by_text
- select_by_value -> select_option_by_value
- verify_alert_is_present -> verify_alert_present
- verify_alert_is_not_present -> verify_alert_not_present
- verify_cookie_exists -> verify_cookie_present
- verify_is_enabled -> verify_element_enabled
- verify_is_not_enabled -> verify_element_not_enabled
- verify_is_selected -> verify_element_checked
- verify_is_not_selected -> verify_element_not_checked
- verify_is_visible -> verify_element_displayed
- verify_is_not_visible -> verify_element_not_displayed
- verify_exists -> verify_element_present
- verify_not_exists -> verify_element_not_present
- verify_text -> verify_page_contains_text
- verify_text_in_element -> verify_element_text
- wait_for_element_not_exist -> wait_for_element_not_present
- wait_for_element_visible -> wait_for_element_displayed
- wait_for_element_not_visible -> wait_for_element_not_displayed

**Removed Actions**
- assert_contains
- assert_equals
- assert_false
- assert_true
- verify_selected_option

**Comment by vietch2612** [comment]
Hi luciano,

When you release that feature? I really want to use the action `javascript_click` because I'm stuck with error `element not clickable at that point ...`

**Comment by lucianopuccio** [comment]
@vietch2612 it's in progress

**Comment by lucianopuccio** [comment]
Adding:
* get_element_text
* get_element_value
* verify_element_has_focus
* verify_element_has_not_focus

Renaming:
* set_alert_text -> send_text_to_alert
* verify_element_attribute_value -> verify_element_attribute
* verify_element_attribute_value_is_not -> verify_element_attribute_is_not

Removed:
* wait_for_alert_not_present

**Comment by r-roos** [comment]
@lucianopuccio got a request here:

a get_data helper function that gives direct access to the "data" object (similar to get_browser).

Goal to have easier access from pages to the data object instead of passing it all the time from tests

**Comment by filiprichtarik** [comment]
what is the benefit of deprecating assert_* actions ?

**Comment by luciano-renzi** [comment]
Completed in 0.6.0

@r-roos get_data was added

@filiprichtarik the deprecated actions were assert_contains, assert_equals, assert_false, assert_true. If you are referring to these, the rationale was that there were a lot more comparisons left out. 
The assert statement should be used instead of having an action for each possible comparison.

Alternatively, a general assert action could be added: assert_condition(condition, error_message) where condition is a boolean expression. Let me know what you think.

I'll add a 'new actions part II' ticket soon.
