### ISSUE TITLE
Quote characters escaped during saving of the webelement identifier in GUI

### ISSUE THREAD

**Issue by Naadaa** [golemhq/golem#107]
When entering a value for webelement xpath selector and after saving it, in code preview all quote characters are escaped (\"). This may occur due to the JSON.stringify(object) method, as when the object is called  most probably JSON.parse(object) is not called to return correct values from the object.
JSON.stringify(object) method can be found in golem/gui/static/js/page_object_code.js, function savePageObject()

**Comment by luciano-renzi** [comment]
Thanks. This is the expected behavior.
