### ISSUE TITLE
Environment Hooks or Modifications

### ISSUE THREAD

**Issue by rothnic** [golemhq/golem#126]
I am looking to use Golem for QA testing of a website. My plan is to setup a bunch of general use-case oriented tests that make sure basic functionality and data is there.

I'm also responsible for building and executing AB tests for the site, which we use Optimizely for. The idea was that I could build an AB test, then execute a suite of QA tests that should still work with the changes applied.

The issue is that we have multiple ways of applying changes to our site. Sometimes it will be controlled by a cookie if the changes are served by our backend, sometimes cookies will also be used to identify who should get the variant, and/or I can force variations with url parameters.

As is, unless I'm missing something, I'd have to modify the actual tests, rather than treating these changes as more associated with an environment. So, I wanted to see what other people thought about extending the Environment concept to allow further modification before the tests associated with a Suite are executed.

**Comment by r-roos** [comment]
The current implementation of the environment.json file allows you to add extra information to the environment.

Something I use at our tests in order to add build numbers and branch names:
environment.json
```
{
    "test-build": {
        "url": "https://some.url",
        "branch_name": "develop",
        "build_number": 1
    }
}
```

Your variables will be available under "data.env.branch_name" etc.  This allows you to set these settings prior executing tests.

**Comment by lucianopuccio** [comment]
As @r-roos points out everything inside an environment definition is injected into the test under data.env. See https://golem-framework.readthedocs.io/en/latest/test-data.html#environments.

Besides this, data **for each test** can be stored in a CSV or inside each test. 

If data changes before each execution it would need to be passed through the command line. Currently not possible.

Another solution I had in mind was for a way to define global data using a single file (placed in the project folder?) and made available to every test. And global data for a specific environment.
```project/data.json``` -> global data
```project/data_<env_name>.json``` -> global data for <env_name> only.

But anyway, this is open for suggestions.

**Comment by luciano-renzi** [comment]
closing 👍
