### ISSUE TITLE
Announcement: Moving project to a Github organization

### ISSUE THREAD

**Issue by lucianopuccio** [golemhq/golem#131]
I would like to announce that I will be moving this and some related repos to @golemhq org. 

I'm pleased with the feedback the project has got so far and thankful for all the contributions. I want to see it grow to its full potential. This change will help keep things more organized.

Also, I'll be renaming my username shortly after.

**Comment by lucianopuccio** [comment]
Yes, the license will remain the same.

**Comment by filiprichtarik** [comment]
congratulations to the decision :) 
few questions though:

will the pypi project stay the same or change as well ? 
could you please fix and release webdriver manager before move (#116)?

**Comment by lucianopuccio** [comment]
> will the pypi project stay the same or change as well ?

Yes, pypi project will remain the same. In the future I'd like to see if we can drop the "-framework" as in "pip install golem". But we'll see. I'll create a new announcement if that happens.

> could you please review and merge and release webdriver manager fix before move (#116)?

Done, thanks for the PR.

**Comment by lucianopuccio** [comment]
It's done.

Clones should update the remote url:
```git remote set-url origin https://github.com/golemhq/golem.git```

For forks:
```git remote set-url upstream https://github.com/golemhq/golem.git```

\* or the equivalent for SSH.
