### ISSUE TITLE
User Authentication 

### ISSUE THREAD

**Issue by danielmaddern** [golemhq/golem#132]
Golem is probably getting to a state where we should start looking at some sort of user management area. 

@lucianopuccio This is my first Flask project, do you have any experience or preferences with the existing Flask user addons?

**Comment by luciano-renzi** [comment]
Hey @danielmaddern 
> do you have any experience or preferences with the existing Flask user addons?
Not of the top of my head, besides Flask-login which is currently being used.

What would be the most important features to add first?

**Comment by luciano-renzi** [comment]
Passwords are now hashed and there is a user management view and a profile view in the UI
