### ISSUE TITLE
Generate static html report after execution

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#134]
Static HTML report should be generated after execution if requested.

* add arg to golem run command to generate static HTML report
* add setting key, same as above
* refactor report code.
* move all report code to its own package

**Comment by r-roos** [comment]
I have a request for this one:
- Include the test case description in the generated html report. Right now only the test name + executed steps are parsed to the html report.

**Comment by luciano-renzi** [comment]
@r-roos the report now has an expandable section for each test with logs, steps, description, and screenshots.

The option to reduce screenshot size has been implemented as well.
