### ISSUE TITLE
Explicit actions import

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#136]
Currently golem.actions is imported implicitly into the test. This negates the use of code completion when using an IDE. The GUI test builder drops any import statement when saving a test.

The golem.actions module should be imported explicitly to a test by default with a setting key to override this (to keep the current behavior)

Example:
```
from golem import actions


def test(data):
    actions.navigate('http://...')
    actions.click('#myId')
    actions.assert_title('My Title')
```

**Comment by lucianopuccio** [comment]
Originally proposed here #70

**Comment by luciano-renzi** [comment]
0.9.0
