### ISSUE TITLE
Add conditional tests 

### ISSUE THREAD

**Issue by pedroporto070** [golemhq/golem#140]
Is it possible? Add if/else or try/catch

**Comment by lucianopuccio** [comment]
So if I understand correctly, the question is can you add control structures inside the test. The answer is yes, you can. However, the GUI test builder cannot parse complex code blocks. It can only parse function call statements (at least for the moment).

So if you are planning on using the GUI to create tests then you should move control structures + try/excepts to functions in page objects (which by the way is in general a good practice). The GUI has a *test code* view, that one does not have any limitations.

If you have other questions try gitter: https://gitter.im/golem-framework/golem

Regards
