### ISSUE TITLE
Feature - internal data/secrets functionality 

### ISSUE THREAD

**Issue by r-roos** [golemhq/golem#144]
Hi everyone, 

I have been working on a feature to have some sort of internal data/secret storage during test execution. The main goal of this storage is to hide the content in the golem test reports, which is the default behaviour of _environments.json_ and the _data_ object. 

The PR can be reviewed @ #143 

1. Passwords
2. Storing environment details irrelevant for the test report, like the database host, schema or port used in your test environment.

Features included:
- secrets.json can be added on project level
- secrets.json is created by default when creating a new project
- secrets can be added & retrieved via actions.store_secret(key, value) & actions.get_secrets()

Remark, there is no GUI element to adjust the content of *secrets.json* unlike *environments.json*

**Comment by r-roos** [comment]
@luciano-renzi requesting a review of this feature.

**Comment by luciano-renzi** [comment]
0.6.2
