### ISSUE TITLE
Feature request - when running tests via CLI golem should use exit status 0/1 depending if there are failed tests

### ISSUE THREAD

**Issue by r-roos** [golemhq/golem#145]
Feature request: When using the CLI it would be great if Golem can set the exit status to:

0 -> In case no tests failed
1 -> In case a test failed 

Having a proper exit status on failing tests will help when using Golem in CI/CD pipelines, as it will enable a pipeline to react on the exit status.

**Comment by luciano-renzi** [comment]
Implemented in 0.7.0, thanks @r-roos!
