### ISSUE TITLE
Add tags to tests

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#147]
I want to add a list of tags to a test.

AC:
* A test can have a list of tags: ```tags =  ['tag1', 'tag2']```
* When running a suite tests can be filtered by tags
* A suite can have 'tags' attribute; add to GUI suite builder
* Tags can be passed to the run command: ```golem run foo bar --tags tag1 tag2```
* -t argument should be used for tags instead of threads

**Comment by luciano-renzi** [comment]
Tags should work as a filter: 
```
golem run project suite --tags foo  # run all the tests of 'suite' that have 'foo' tag
golem run project . --tags foo      # run every test with 'foo' tag
golem run project folder/ --tags    # run every test in 'folder' with 'foo' tag
```

**Comment by r-roos** [comment]
added via https://github.com/golemhq/golem/pull/167

**Comment by luciano-renzi** [comment]
0.8.0
