### ISSUE TITLE
Rename run argument -t|--threads to -p|--processes and suite workers attribute

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#148]
Rename the run command argument -t|--threads to -p|--processes (which is what they actually are). -t will be used for --tags instead.

Rename suite 'workers' attribute to 'processes'.

**Comment by luciano-renzi** [comment]
#147

**Comment by r-roos** [comment]
added via https://github.com/golemhq/golem/pull/167

**Comment by luciano-renzi** [comment]
0.8.0
