### ISSUE TITLE
Suites with multiple environments - running 1 environment after another

### ISSUE THREAD

**Issue by karinamkl** [golemhq/golem#150]
When running suites with multiple environments framework runs 1st test in all environments  specified, then 2nd test in all environments and so on. 
How can I configure run in a way so all tests run in 1st environments first, then all tests in 2nd and so on?

**Comment by luciano-renzi** [comment]
There is no way to force the order of the tests in a suite. For this, you should create a different suite for each environment or run the suite once per each environment (with -e flag). What is the outcome you are trying to achieve?

**Comment by karinamkl** [comment]
I ended up doing just that, created 3 separate suite files for 3 different environments as I need to run whole suite for 1 environment first, then 2nd env and so on. 
What I envisioned is to have a command line statement that will be put into Jenkins to schedule test execution for all 3 environments. Since we can't force order for now it will have to be 3 separate Jenkins projects with 3 command line statements.

**Comment by luciano-renzi** [comment]
The order of the tests should not matter if they should be ready to run in parallel. 
What´s missing right now is a way to define a setup_suite/before_suite function and a before_test/before_each. I asked just to know if this was the case.

Just a heads up. You don't need 3 suite files. You could pass the environment as an argument:
```
golem run my_project my_suite -e env01
golem run my_project my_suite -e env02
```

You could call that command once per environment and then you would ensure the order of the tests environment-wise.

Regards
