### ISSUE TITLE
chrome-remote-headless broken...

### ISSUE THREAD

**Issue by testjenk** [golemhq/golem#151]
https://github.com/golemhq/golem/blob/71d4da2929423137bde436de71faf256d1607756/golem/browser.py#L101

should read:

with validate_remote_url(settings['remote_url']) as remote_url:

**Comment by r-roos** [comment]
Thanks for reporting this issue @testjenk 
Created a PR with your suggested fix: https://github.com/golemhq/golem/pull/154

**Comment by luciano-renzi** [comment]
The fix is implemented in 0.7.0

Thanks!
