### ISSUE TITLE
Report generation customization - type, name and location

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#156]
Enable customizations for the location, type, and name of the generated report.

The report currently is saved in:
```<testdir>/projects/<project_name>/reports/<suite_name>/<timestamp>/execution_report.json```

* Change *execution_report.json* to *report.json*

**Types of reports to generate:**

* Add a --report argument that accepts the types of reports to be generated:
```
golem run project suite --report html junit
```

**Specify where the report is saved:**

* Add arguments to golem run command to customize the location of the generated reports:

    - --timestamp -> optional

    - --report-name ->  file name without the path and extension, default is 'report'

    - --report-folder -> absolute path

**Example 1:**
```
golem run project_name suite_name --report html junit --timestamp 2018.12.12.02.44.22
```

Output:
```
/testdir/projects/project_name/reports/suite_name/2018.12.12.02.44.22/report.html
/testdir/projects/project_name/reports/suite_name/2018.12.12.02.44.22/report.xml
```

**Example 2:**
```
golem run project_name suite_name --report html junit --report-folder /my/report/folder/ --report-name my_report
```

Output:
```
/my/report/folder/my_report.html
/my/report/folder/my_report.xml
```

**Comment by danielmaddern** [comment]
This sounds pretty good, I'd use it for sure.. Happy to work on this next week unless someone else wants to do it.

**Comment by luciano-renzi** [comment]
Sure, go for it.

I pushed the changes for the static HTML report: https://github.com/golemhq/golem/commit/f15a97a608f2d10a4c3c4807399429ebb3415fa6

I added two reports: "html", "html-no-images"

To generate HTML report:
```python
from golem.gui.gui_utils import generate_html_report

# static HTML report
generate_html_report(project, suite, execution, report_directory, report_name)

# static HTML report no images
generate_html_report(project, suite, execution, report_directory, report_name, no_images=True)
```

**Comment by luciano-renzi** [comment]
0.7.0
