### ISSUE TITLE
Add setting to customize screenshot extension, size and compression

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#158]
Screenshots can take a lot of disk space.

Add a setting key to customize the screenshots extension, size, and compression:

screenshots
* format: PNG, JPG
* quality: 0..100, only for JPGs?
* width, height: set only one to maintain aspect ratio
* resize: percentage

It will require Pillow to be installed separately.

**Comment by r-roos** [comment]
Would this also affect the generated HTML report size ?

**Comment by luciano-renzi** [comment]
@r-roos yes it does

Implemented in 0.7.0
