### ISSUE TITLE
[enhancement] support for "for" loops

### ISSUE THREAD

**Issue by way2github** [golemhq/golem#166]
Currently, "for" loops are not supported. Nice to have this feature in near future. Thanks!

**Comment by r-roos** [comment]
Could you elaborate a bit more on what you are trying to achieve in your test, maybe with an example ? 

A way to achieve loops is by creating a page with a loop function and use that particular function in your test.

**Comment by way2github** [comment]
Suppose we need to import the same document for 5 times inside the "test" method using the following code:
for x in range(5):
        send_keys(('xpath', '//input[@id="fue_uploadfile0"]'), "C:\\doc_import\\Invoice.jpeg")
        click(('xpath', '//button[text()="Import"]'))
        wait_for_element_displayed(('xpath', '//td[text()="Imported Successfully"]'), 60)

If we write this piece of code in the **code** view of a test, and then toggle to **preview** mode, then add one more step and save the test and go back to **code** view again, the for loop is no more in proper format. **for x in range(5):** changes to **for_x_in_range(5)**

Creating a page with a loop function might be useful when the number of steps are less. But in case of larger script (that needs to be repeated) which uses **data** (more than 10 parameters), will page be a good option?

Thanks!

**Comment by r-roos** [comment]
Thanks for your example. Indeed in the current state Golem does not really support this kind of syntax in the tests itself, however in pages it does. Golem encourages to place complex logic into pages which can be re-used in multiple tests. I would recommend placing your example in a page as well. 

Using your example in a page style:

The test:
```
description = ''

pages = ['sample_page']

data = [
    {
        'image': 'C:\\doc_import\\Invoice.jpeg',
    },
]

def setup(data):
    pass

def test(data):
    sample_page.submit_multiple_times(5, data.image)

def teardown(data):
    pass
```

The page
```
from golem import actions

picture_input = ('xpath', '//input[@id=\"fue_uploadfile0\"]', 'picture_input')
submit_button = ('xpath', '//button[text()=\"Import\"]', 'submit_button')
succes_upload_notice = ('xpath', '//td[text()=\"Imported Successfully\"]', 'succes_upload_notice')


def submit_multiple_times(amount, image_full_path):
    for x in range(amount):
        actions.send_keys(picture_input, image_full_path)
        actions.click(submit_button)
        actions.wait_for_element_displayed(succes_upload_notice, 60)
```

**Comment by r-roos** [comment]
@luciano-renzi In your view would the suggested changes in: https://github.com/golemhq/golem/issues/137 https://github.com/golemhq/golem/issues/136  would have any effect on how the Golem webeditor behaves on more complex python structures ?

**Comment by luciano-renzi** [comment]
Hi @way2github, I agree with @r-roos, the best solution for this is to use a function in a page. 

If the issue is the number of parameters, the data of the test is available in golem.execution.data. Example:

**page1.py**
```
from golem import actions, execution

picture_input = ('xpath', '//input[@id=\"fue_uploadfile0\"]', 'picture_input')

def submit_something():
    actions.send_keys(picture_input, execution.data.image_full_path)

```


I added #168 so instead of beaking the preview view when the test syntax is not the expected, the statements that cannot be parsed will be displayed as code blocks. Statements what can be parsed to "steps" are only function calls, anything else will be displayed as code blocks. That is as far as the test parser will go.

> @luciano-renzi In your view would the suggested changes in: #137 #136 would have any effect on how the Golem webeditor behaves on more complex python structures ?

Not really, but check #168 and let me know what you think :P 

Thanks both.
