### ISSUE TITLE
Duplicate strings in PageObjects file when working from gui

### ISSUE THREAD

**Issue by Semen-kisliy** [golemhq/golem#169]
I've created page in pages folder from gui, as the PageObjects required. After filling it looks like this in python file:
![pic](https://user-images.githubusercontent.com/8688695/54340018-820ca580-4647-11e9-93ef-3771ddcf4c19.png)

In file is about 30 elements and after some obscure reasons, after pressing "Save", or deleting elements from gui, there are appears additional strings in the top of the file:
![pic2](https://user-images.githubusercontent.com/8688695/54340283-137c1780-4648-11e9-8cbb-671d1ecf37bb.png)

They appears only in *.py file, not in gui. And in fact, this strings are duplicates of already existing ones.
I've notieced this after I've deleted one string from gui, pressed "Save", reload page and this string reveals again.

Maybe it's expected behavior, but not sure.

**Comment by luciano-renzi** [comment]
Nice find! the lines that included 'import' were throwing the parser off.
