### ISSUE TITLE
UnicodeDecodeError problem

### ISSUE THREAD

**Issue by LuanShiZhiJian** [golemhq/golem#178]
I input Chinese context in web module page input box，the Console of windows will show the error message:UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 120: illegal multibyte sequence.

![image](https://user-images.githubusercontent.com/41558924/63241757-6d33de00-c287-11e9-875a-090b7dff274b.png)

Would you please advise?

**Comment by luciano-renzi** [comment]
Thanks for the report. I will take a look at it.

**Comment by luciano-renzi** [comment]
Fixed in 0.9.1
