### ISSUE TITLE
How can we execute golem from Jenkins?

### ISSUE THREAD

**Issue by qamadhu** [golemhq/golem#182]
Hi,
Could you please guide me how can we trigger golem project from Jenkins
or
Do we have any Jenkins -plugin for golem integration.

Thanks,
Madhu

**Comment by Meghrikyan** [comment]
Let's assume you have 
   a. repository with your Golem project, 
   b. configured Jenkins.
Target is to create "Jenkins Freestyle Project", and be able to see reports somewhere (to see it somewhere we have script "A", that exports/converts Golem report into format acceptable for other system, and uses some API to push results).

1. Create New Item
2. Add Name and select "Freestyle Project"
3. Select "code management repository" for Golem project
4. Add "build step" - "Execute shell". 
5. Here you can specify all the list of actions needed to prepare browsers, update python modules, etc.

- Click "Build now" button, to start building the project first time, Check the result from "Console output", to find out what is missing.
- I suggest also to uncheck "Delete workspace before build starts" checkbox.

6. Add "build step" - "Execute shell". use "golem run project_name test_name_or_suite_name". 
7. For reporting it is needed to add another - "Execute shell". Keep in mind that "present working directory" pwd, is the project folder. You can find it somewhere in "/var/lib/jenkins/workspace".

**Comment by luciano-renzi** [comment]
Alternatively here's a guide: https://golem-framework.readthedocs.io/en/latest/guides/run-from-jenkins.html
