### ISSUE TITLE
Highlighting a Web Element on Webpage during runtime

### ISSUE THREAD

**Issue by ATTO-DT** [golemhq/golem#203]
on runtime when element click, verify and other operation it should be highlight elements.
so in this case user can see highlight element in Realtime when execution happening and also in attach screenshot for every step.

**Comment by ATTO-DT** [comment]
I have created custom function on page and have used in Test page and it's worked
https://gist.github.com/dariodiaz/3104601#file-highlight_sel_element-py
![image](https://user-images.githubusercontent.com/71543231/114732190-f272dd00-9d5f-11eb-9220-c974f7e5d862.png)

**Comment by luciano-renzi** [comment]
I don't know if the amount of users that would like this behavior is enough to implement it. Though it should be something that can be turned on or off. I'll keep this in mind for the future. Thanks

**Comment by ATTO-DT** [comment]
based on setting we can do setup for highlight like we have screenshot for.
highlight_on_step with true and false if user want to make highlight so can make change on setting(bydefault  it should be false only)

Why it's required : some time user need to look into screenshot  for debug which element is clicked on each step.(like example  have two save button  on web page then through highlight it will easy to track  on screenshot which one clicked on which step)
