### ISSUE TITLE
Single Test case report not able to see on GUI

### ISSUE THREAD

**Issue by ATTO-DT** [golemhq/golem#204]
single test case report only  available when  finished execution  of test case  only.
but User want to see previous report  of single test case  then not able to found anywhere in report page.
good thing here is we have single test folder in report folder so this all report  can show on  report page with diff container name of single test case.

Note: if possible previous report should available on Test page also with health Container.(like have feature when click on suite with health Container)

**Comment by luciano-renzi** [comment]
That's correct. This will be implemented by #201 Every execution be it single test or suite will have the same folder structure and it will be visible in the report UI
