### ISSUE TITLE
Realtime Autocomplete suggestion in code editor

### ISSUE THREAD

**Issue by ATTO-DT** [golemhq/golem#214]
if possible user should get autocomplete suggestion in code editor like
suppose if user use navi in code editor so it should suggest navigate.

why it's required : if user want to add code in code editor itself so user should know what are  the action user can use like if user type asset_ so it should suggest all action type of asert_

**Comment by ATTO-DT** [comment]
we can use this one [Autocomplete ](https://github.com/mvickymca/codemirror_python_autocomplete)  but need to use ctrl-space  It will better if we can make it Realtime autocomplete suggestion

**Comment by luciano-renzi** [comment]
I think this is a good idea 👍

There's an api endpoint that returns the list of actions: https://github.com/golemhq/golem/blob/master/golem/gui/api.py#L60

**Comment by ATTO-DT** [comment]
Hi Luciano
yes, thanks
I almost near to implement this feature planning to make like this below
suppose user typing sendke so it should give autocomplete suggest sendkeys(element,text)
