### ISSUE TITLE
Test Should be draggable on Suite page.

### ISSUE THREAD

**Issue by Sunil-Rathore** [golemhq/golem#217]
suppose have two test below and user want to run Login_Test1 before the Login_Test so it should be draggable means user can drag the Login_Test1 before  the Login_Test.
 
![image](https://user-images.githubusercontent.com/71543231/123902704-effd4800-d98a-11eb-9782-25d435597e03.png)

@luciano-renzi  what your approach for this.

**Comment by HybridAU** [comment]
@luciano-renzi might have some insight that I don't but I think as a general rule, tests should be independent, so they can be run in any order without affecting one another, for example you can use multiple processes and run tests in parallel.

![image](https://user-images.githubusercontent.com/1610265/123935146-89961b00-d9c6-11eb-8326-25bbeaa4a430.png)

I'd first look to see if you can make your tests independent, but if that's not possible in your situation for whatever reason, maybe your best option is to join them into a single test.

**Comment by luciano-renzi** [comment]
I agree it's good practice to write tests independent of other tests.

In version 0.10.0 you can add more than one test to a test file and if you are using Python 3.6+ the order of the tests in the file should be preserved. See this as an example: https://github.com/golemhq/golem-tests/blob/master/projects/golem_gui/tests/test_list/add_folder_validation.py

I did some testing and the order of execution of the tests of a suite is the same order they are listed in the suite (I tried on 3.7). So you can specify the order of execution if you use the "code view" of a suite and manually add each test to the list.

Now adding this feature to the preview view I don't see as high priority but if you want to tackle it, then go for it and feel free to reopen the ticket.
