### ISSUE TITLE
Serializing Tests within the suit

### ISSUE THREAD

**Issue by Mozogul** [golemhq/golem#234]
For example i have 2 tests 
TC_1_Login : In this test case we are navigating to given url and validating login info 
TC_2 Create customer : In this test case we are creating customer 

I added both Tests in to a suit and i want to execute TC_1 and TC_2 serially  within one session but when i run the suit 
browser is closed after " TC_1_Login " case is executed  and TC_2 is failed since login case browser is closed and logged in session is no more.

**Comment by ATTO-RATHORE** [comment]
Please check it #229  hope it will help to continue login session.
it's gud practice to use  new session for every test within the suite. if want to skip login then need to make custom browser setting.

**Comment by Mozogul** [comment]
Thanks Sunil
