### ISSUE TITLE
Test Results of Single test execution not captured in reports

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#40]
On creating an single test and executing by UI, on test failure the results are not captured in Reports for later reference.
**Test Failure Console Output**
![testfailurescenario](https://user-images.githubusercontent.com/9512482/31855725-edc49b66-b67e-11e7-8497-24887f8604e3.png)

**Empty Reports**
![golem_emptyreports](https://user-images.githubusercontent.com/9512482/31855700-884505a0-b67e-11e7-87dc-631bba4fcb1c.png)

**Comment by lucianopuccio** [comment]
Currently only suite executions are displayed in the reports. Single tests reports are still stored as json files and can be found in the folder /<project>/reports/single_tests/, although it would be better if they were also in the html reports. I'll see how can this be implemented, thanks!
