### ISSUE TITLE
Placing an existing test inside a newly created module (a folder from Windows Explorer) loses the test

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#42]
Placing An Existing Test Inside a newly Created Module( a folder from Windows Explorer) loses the test.
**Env:**
Windows 7/8
Python: 3.4.4
Golem: 0.2.2

**Steps:**
1).Create an Test called 'Test1'directly inside tests folder.
2).Create a folder named 'Module1' from windows explorer inside tests folder and cut paste the 'Test1' inside it.
3).By GUI, try to access 'Test1' by clicking on it by expanding 'Module1' folder and clicking on 'Test1'.
4).Will get the error as attached.

Note: Did not find a way to add a Module from UI so added folder from windows explorer.

![golem_openinganexistingtestfrommodulefolderinui](https://user-images.githubusercontent.com/9512482/31865199-b82211ea-b738-11e7-8ef2-90452c35667d.png)

**Comment by lucianopuccio** [comment]
The thing is that 'modules' in Golem are actually Python packages and they require a __init__.py file in them to work (this file can be empty)
https://stackoverflow.com/questions/448271/what-is-init-py-for

You can create a module from the gui, just append a dash at the end, ie: 'some_module/'

I'll leave this open to see if there's a workaround when adding folders from the windows explorer. Thanks!
