### ISSUE TITLE
Dynamic test filtering based on some label/tag like 'smoke','regression', 'fast','slow'.

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#43]
How can user dynamically filter tests  based on some labels or tags like 'smoke','regression', 'fast','slow' from high level folder instead of physically dividing tests by creating separate folders like regression/smoke or fast/slow.

This is like saying execute all tests with 'fast' tag irrespective of any folder hierarchy in which they actually reside.

**Comment by lucianopuccio** [comment]
Having the possibility to add tags to a test and then filter the tests when creating a suite would be nice!

**Comment by luciano-renzi** [comment]
I'll continue this here: #147
