### ISSUE TITLE
Differentiating between soft vs. hard assertions inside tests

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#46]
How framework supports hard vs. soft assertions inside an test.

**Terminology**
Hard Assertions:Test execution stops as soon as assertion failure found.
Soft Assertions:Test execution continues even if assertion failure found.

**Comment by lucianopuccio** [comment]
Currently all assert* and verify* functions are hard assertions, they will stop the test.
From what I understand the result of a soft assertion would be just an error message in the execution log, right? if this is the case, this could be emulated by using the logger:

```
from golem.execution import logger

def func():
    logger.error('some soft assertion')  # output: "16:41:34.175 ERROR some soft assertion"
```

Do you know a framework that has these 2 types of assertions?
thanks

**Comment by vishal-agg** [comment]
Please refer [TestNG](https://stackoverflow.com/questions/30030995/hard-and-soft-assertions-in-testng).
Thanks

**Comment by lucianopuccio** [comment]
Hey Vishal, upon some research on the matter, it's not a bad idea to implement these two types of assertions. For consistency with Selenium IDE, verify* should be used for soft assertions and assert* should be used for hard assertions. I will be working on this. Thanks for the input.

**Comment by vishal-agg** [comment]
You are welcome, Luciano. Please let me know if you need more information.

**Comment by lucianopuccio** [comment]
Since 0.6.0 there are soft and hard assertions: https://golem-framework.readthedocs.io/en/latest/golem-test-framework.html#assertions-and-verifications.
