### ISSUE TITLE
Tests Dependencies/relations

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#47]
How can user set dependencies between multiple tests?

**Example:**
Test1->Test2 to TestN : In order to execute Test2 to TestN , Test1 should be executed successfully first as that is the primary/basic test for the module.

**Comment by lucianopuccio** [comment]
A possible solution for this would be a setup function at suite level?, check out my answer on #54

**Comment by vishal-agg** [comment]
Yes, you are correct.It makes more sense to have a function to do this at the suite level.
