### ISSUE TITLE
How to accept ssl certificates in Chrome and Firefox?

### ISSUE THREAD

**Issue by zeeshanyshaikh** [golemhq/golem#52]
Where to add capabilities to accept trusted SSL certificates in Chrome and Firefox browsers?

**Comment by danielmaddern** [comment]
Is this when using http_get and http_post? 

if so, quick work around is to use requests.get(url, verify=False). 
@lucianopuccio working on this one at the moment, will have a pull request for you today hopefully.

**Comment by danielmaddern** [comment]
pull regrest for http_get and http_post submitted #58 

Still not sure if this is the same issue as @zeeshanyshaikh is having.

**Comment by zeeshanyshaikh** [comment]
Sorry for the late reply..but am using selenium to invoke the browser with custom ssl certificate.
