### ISSUE TITLE
Setup and TearDown on Suite level

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#54]
How can user define setup and teardown actions on suite level?

**Comment by lucianopuccio** [comment]
Currently not possible. I'm planning on implementing something like this, please check http://golem-framework.readthedocs.io/en/latest/golem-test-framework.html if you have time. It's the draft of what I'm planning to implement.

Thanks!

**Comment by vishal-agg** [comment]
Looks good.Thank you.
