### ISSUE TITLE
The way the gui works defeats my IDE

### ISSUE THREAD

**Issue by mark0978** [golemhq/golem#70]
So if I want help with completion in my IDE using golem, I need:

    from golem import actions
    from ..pages import MerchantFormPage1, MerchantFormPage2

and

    actions.click(something)

This allows my IDE to help me with the actions.  But the golem GUI doesn't strip the actions part from the statements, so I'm stuck with the gui showing actions.click

This might be less of an issue if I could insert steps into a test without having to use my IDE to insert them because the GUI only supports appending.  PS, just discovered drag and drop in the GUI (completely by accident) so insertion is a thing.

**Comment by mark0978** [comment]
I think I might be able to work around the first problem with from golem.actions import *

**Comment by luciano-renzi** [comment]
Implemented in 0.9.0
