### ISSUE TITLE
Once I get into the debugger, how do I use the page objects?

### ISSUE THREAD

**Issue by mark0978** [golemhq/golem#71]
The ones in the code base aren't really PageObjects so I can't import them and instantiate them, and I don't see how to get the page objects from this?
```
>>> locals().keys()
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'time', 'uuid', 'os', 'importlib', 'string', 'rand', 'selenium', 'Keys', 'ActionChains', 'EC', 'WebDriverWait', 'requests', 'TextNotPresent', 'ElementNotFound', 'get_browser', 'browser', 'execution', '_run_wait_hook', '_capture_or_add_step', 'assert_contains', 'assert_equals', 'assert_false', 'assert_true', 'capture', 'clear', 'click', 'close', 'debug', 'get', 'mouse_hover', 'navigate', 'press_key', 'random', 'refresh_page', 'select_by_index', 'select_by_text', 'select_by_value', 'send_keys', 'set_window_size', 'step', 'store', 'verify_exists', 'verify_is_enabled', 'verify_is_not_enabled', 'verify_is_not_selected', 'verify_is_not_visible', 'verify_is_selected', 'verify_is_visible', 'verify_not_exists', 'verify_selected_option', 'verify_text', 'verify_text_in_element', 'wait', 'wait_for_element_not_exist', 'wait_for_element_not_visible', 'wait_for_element_enabled', 'wait_for_element_visible', 'http_get', 'http_post', 'verify_response_status_code', 'vars_copy', 'console_exit', 'code', 'readline', 'exit'])
```

**Comment by lucianopuccio** [comment]
Hi Mark,

You can import pages from the 'pages' package: 
```from pages import page_name```

another option is to import it with the full path: 
```from projects.project_name.pages import page_name```

If this does not work, let me know, this functionality still needs some improvements. thanks

**Comment by lucianopuccio** [comment]
Examples:
<img width="857" alt="screen shot 2017-12-07 at 9 28 59 pm" src="https://user-images.githubusercontent.com/2257588/33745537-2f73ad18-db96-11e7-8a9f-fc31f0eeaece.png">
<img width="857" alt="screen shot 2017-12-07 at 9 26 50 pm" src="https://user-images.githubusercontent.com/2257588/33745539-2fade44c-db96-11e7-9653-854c74f8f5d6.png">
