### ISSUE TITLE
Differentiate error from failure

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#72]
Currently the test can be 'passed' or 'failed'

The 'fail' status should be differentiated in two: 'failure' and 'error'

If an assert action fails the test should be marked as 'failure'

Any other error or exception should mark the test as 'error'

**Comment by Meghrikyan** [comment]
Can you please explain how is working wait_for_element_displayed?
For wait_for_element_not_displayed if the element is displayed, then it marks as "FAILED", which is correct.
Same i want to have here for "wait_for_element_displayed". If the element was not displayed within some period, then test expected to be "FAILED", but it is reported as "code error".
