### ISSUE TITLE
Appium Integration 

### ISSUE THREAD

**Issue by danielmaddern** [golemhq/golem#77]
Hey @luciano-renzi ,

Have you started on this? I started integrating appium into 0.4.1 yesterday.. 
Hoping to have golem working with Android today, but I think there's some significant changes needed to browser.py to get the desired capabilities from a test case. 

Did you want to create a feature branch on here that I can do PRs and people can pull down if they want to test/contribute?

Also, Have you got anywhere we can discuss feature implementation, or creating an issue is the best place?

Cheers,
Daniel

**Comment by lucianopuccio** [comment]
Hi Daniel

> but I think there's some significant changes needed to browser.py to get the desired capabilities from a test case.
I think it would be best if we use a new module 'app.py' that is analogous to 'browser.py' so it is kept as two separate entities, and each one has the abstraction of a web browser and a mobile app respectively.

> Did you want to create a feature branch on here that I can do PRs and people can pull down if they want to test/contribute?
I created the branch feature/appium

> Also, Have you got anywhere we can discuss feature implementation, or creating an issue is the best place?
That would be great. What would you recommend? I was thinking about gitter or google groups, or both.

**Comment by lucianopuccio** [comment]
added gitter
