### ISSUE TITLE
Add more golem actions

### ISSUE THREAD

**Issue by luciano-renzi** [golemhq/golem#80]
## New Actions

**fail(message)** : mark the test as failure, stop, jump to teardown
**error(message)** : add an error to the test, the test should continue, will be marked as error at the end
**verify_url(url)** : verify the current url
**verify_url_contains(url_substring)** : verify the current url contains the url_substring passed as argument
**get_current_url()** : returns the current url 
**tab management** (open tab, close tab, get current tabs, switch to tab)
**alerts** (verify alert is present, verify alert text, close alert)
**verify_window_title**
**verify_window_title_contains**
**scroll**
**IFrame** (switch to IFrame)
**get_element_text(element)** : returns the text of an element

## Current Actions Refactor

**capture()** : rename to screenshot()
**verify_text_in_element(element, text)** : rename to verify_element_text(element, text)

**Comment by r-roos** [comment]
Can we also request some actions in this issue ? I would like to have the following:

get_text: returns the text of an element

**Comment by lucianopuccio** [comment]
Sure, go ahead!

Since this is a standalone function and not a webelement method _get_element_text_ would be best

**Comment by IvanPenev92** [comment]
I'm pretty new at Golem and probably this feature is already implemented, but I didn't figure it out, but just in case it's not: a function to close a specific tab would be very useful.

**Comment by thanhlelgg** [comment]
@IvanPenev92  This feature is already planned to be implemented in the description above (Tab management)
