### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by johnrbnsn** [golemhq/golem#86]
In the adding-tests.md docs, the `teardown()` method needs to have a 'data' parameter, otherwise it will have an error. 

TODO: Change line 68 of [adding-tests.md](https://github.com/lucianopuccio/golem/blob/master/docs/source/adding-tests.md) from `def teardown():` to `def teardown(data):`

**Comment by devilrancy** [comment]
@johnrbnsn please change and create a PR which is recommended.

**Comment by r-roos** [comment]
Closing this issue as I believe the documentation no longer contains this error
