### ISSUE TITLE
AttributeError: 'module' object has no attribute 'module_from_spec'

### ISSUE THREAD

**Issue by RichardProsser** [golemhq/golem#90]
https://github.com/lucianopuccio/golem-demo#run-a-test-suite-from-the-console
http://localhost:5000/project/store_demoqa/page/header/

<img width="1860" alt="screen shot 2018-02-08 at 16 27 29" src="https://user-images.githubusercontent.com/6561811/35984995-8422b04c-0ced-11e8-96be-c6f236c1cc21.png">

**Comment by r-roos** [comment]
@RichardProsser is it possible to provide steps to reproduce this error ?  I opened the demo project myself today and I have no issues loading the store_demoqa/page/header/ page:
![image](https://user-images.githubusercontent.com/32699953/37054477-3f5f7520-217f-11e8-80bf-b5853de82afb.png)

**Comment by luciano-renzi** [comment]
Stale. Closing.
Just in case, Python 3.4 is no longer supported.
