### ISSUE TITLE
Issues with page objects

### ISSUE THREAD

**Issue by ArtemSukhomlyn** [golemhq/golem#92]
OS name and version - Win 10 (x64)
    Python version - Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
    Golem version - I don't know where I can check it (latest installed with pip)

I faced with the following problem:
For unknown for me reasons golem doesn't save elements in page objects (without showing any tips or message) or doesn't show objects if I fill it in <Code> mode.
Sometimes it erased objects if saved it before.
More details please see on attached videos:
http://recordit.co/by6VOYYFXk
http://recordit.co/yzWWx4bUxC

**Comment by r-roos** [comment]
I am unable to recreate this problem on both windows and mac using the pip version of golem (using chrome on both machines). 

In case you used an older version of golem it is recommended to clear the browser cache (learned this from @lucianopuccio)

**Comment by ArtemSukhomlyn** [comment]
Hi there.
After some period I've returned to discovering of  Golem and again faced with the same issue.
 Now I investigate behavior little bit deeper  (F12 in browser) and  can definitely say that it is not cache ![save_error_golem](https://user-images.githubusercontent.com/14799785/44605913-d0656e80-a7f3-11e8-9ee8-39227a3938df.png). Stacktrace  for my case almost the same like for the issue https://github.com/lucianopuccio/golem/issues/85 with title builtins.TypeError
TypeError: 'NoneType' object is not subscriptable
![stack-trace_golem](https://user-images.githubusercontent.com/14799785/44606173-d871de00-a7f4-11e8-834b-0b853ddfd618.png)
My assumption that it can be somehow connected with Python version (v.3.6)

**Comment by ArtemSukhomlyn** [comment]
I've check my assumption, after re-installation (downshifting) of python 3.6.3 ->3.4.4 Golem works as expected (for now)
![ok](https://user-images.githubusercontent.com/14799785/44607493-50420780-a7f9-11e8-9752-6c59717bf39a.png)

**Comment by luciano-renzi** [comment]
Closing. Reopen if this is still happening. Thanks.
